from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer


class MusicChatBot:

    def __init__(self, name):
        self.chatbot = ChatBot(name)
        self.trainer = ListTrainer(self.chatbot)

    def get_response(self, input_user):
        return self.chatbot.get_response(input_user)

    def train(self):
        self.trainer.export_for_training('export.json')
        self.trainer.train([
            "¿qué es la música?",
            "arte de combinar los sonidos en una secuencia temporal atendiendo a las leyes de la armonía, la melodía "
            "musica",
            "arte de combinar los sonidos en una secuencia temporal atendiendo a las leyes de la armonía, la melodía "
            "y el "
            "ritmo, o de producirlos con instrumentos musicales.",
            "¿sabes de música?",
            "si tengo conocimientos de música",
            "conoces al artista del año?",
            "dua lipa",
            "canción mas oida del mundo?",
            "the weekend - save your tears",
            "canción mas odiada del mundo?",
            "baby - justin bieber",
            "generos de musica",
            """música clásica,
            jazz,
            blues,
            góspel,
            soul,
            pop,
            rock and roll,
            country,
            disco,
            techno,
            reggae,
            salsa,
            flamenco,
            ranchera,
            hip hop/rap,
            reggaetón,
            metal,
            funk,
            bossa nova,
            música melódica.""",
            "artistas mas famosos de 2022",
            """rauw alejandro,
            justin bieber,
            ed sheeran, 
            bts,
            drake,
            the weeknd,
            post malone, 
            taylor swift.""",
            "quiénes son los beatles?",
            "una banda inglesa muy popular en los 60's",
            "conoces alguna canción de tiktok?",
            "claro que sí. escucha cure for me de aurora.",
            "cuál es el género de música más popular?",
            "de acuerdo statista global consumer survey, el género más popular es el pop contemporáneo para adultos",
            "diferencias entre dream pop y shoegaze",
            "la comunidad shoegaze categoriza el género como centrado en la guitarra, utilizando toneladas de reverberación y efectos de retardo, paisajes sonoros en capas e influencias punk, muy diferente al dream pop.",
            "quién fue michael jackson?",
            "fue una leyenda musical, conocido como el rey del pop.",
            "quién es el rey del pop?",
            "el legendario michael jackson",
            "quién es la reina del pop?",
            "me la pones difícil. disfruta de madonna y de beyoncé por igual 😎.",
            "en qué año surge trip hop?",
            "a mediados de 1980 en bristol, inglaterra.",
            "de quien es el album mezzanine?",
            "el album mezzanine pertenece al grupo massive attack.",
            "quién fue elvis presley?"
            "el gran elvis presley es una leyenda musical, conocido como el rey del rock and roll.",
            "quién es el rey del rock n roll?",
            "el legendario elvis presley",
            "cuántos albums tiene led zeppelin?",
            "led zeppelin cuenta con 9 álbumes de estudio, 9 recopilatorios, 4 en directo y 3 en video.",
            "en qué año salió romances de luis miguel?",
            "el álbum romances de luis miguel es del año 1997.",
            "cuántos discos tiene daft punk?",
            "daft punk cuenta con 4 álbumes de estudio, 1 recopilatorios, 2 en directo y 1 en video.",
            "cuál es el disco más vendido en la historia?",
            "el disco más vendido ha sido thriller de michael jackson.",
            "mtv unplugged más escuchado",
            "probablemente haya sido el mtv unplugged de 1993, con la banda nirvana.",
            "de qué banda es kurt cobain?",
            "nirvana",
            "quién fue freddie mercury?",
            "freddue mercury fue un cantante, compositor, vocalista y líder de la banda inglesa queen. su nombre real era farrokh bulsara.",
            "quién es el vocalista de queen?",
            "farrokh bulsara, mejor conocido como freddie mercury.",
            "quiénes son rammstein?",
            "rammstein es una banda alemana de metal industrial formada en 1994 por los músicos till lindemann, richard z. kruspe, oliver riedel, paul landers, christian lorenz y christoph schneider.",
            "cuál fue el último disco de david bowie?",
            "the gouster.",
            "en qué año ganó leonard cohen el premio príncipe de asturias?",
            "leonard cohen fue galardonado en el año 2011.",
            "quién fue jeff buckley?",
            "fue un músico de rock alternativo, reconocido como el que popularizó 'hallelujah'.",
            "en qué año murió john lennon?",
            "el trágico fallecimiento de john lennon fue el 8 de diciembre de 1980.",
            "quién escribió let it be?",
            "una de las canciones más reconocidas de the beatles fue escrita por el dueto lennon-mccartney.",
            "quién es drake?",
            "aubrey drake graham, conocido simplemente como drake, es un rapero, cantante, compositor, productor discográfico y actor canadiense.",
            "quién canta stand by me?",
            "esa hermosa canción es interpretada por mi buen amigo ben e. king.",
            "en que banda estuvo paul mccartney?"
            "la más famosa globalmente fue the beatles. posteriormente conformó otro grupo llamado paul mccartney and wings.",
            "qué género es pxndx",
            "pxndx es una banda de rock en español originaria de monterrey, nuevo león.",
            "quién fue chuck berry?",
            "charles edward berry (chuck berry) fue un guitarrista, cantante y compositor de rock and roll estadounidense.",
            "qué día murió chalino sánchez?",
            "chalino sánchez falleció el 16 de mayo de 1992.",
            "conoces a los beach boys?",
            "por su pollo que sí, the beach boys es una banda de rock. muy distinguidos por sus armonías vocales y muy influyentes en la era del rock and roll.",
            "quién es jimi hendrix?",
            "jimi hendrix fue un guitarrista, cantante y compositor estadounidense que solo duró cuatro años de carrera profesional. aún así, es considerado uno de los guitarristas más influyentes de la historia del rock.",
            "quiénes son ac/dc?",
            "ac/dc es una banda de hard rock británica-australiana formada en 1973.",
            "cuál fue la canción del mundial de lol de este año?",
            "star walkin' de lil nas x.",
            "qué es un picture disc?",
            "los discos ilustrados (picture disc) son un tipo de discos fonográficos que muestran imágenes en su superficie de reproducción.",
            "de qué país es el grupo el columpio asesino?",
            "el columpio asesino es una banda originaria de pamplona, españa en el año 1999.",
            "en qué año se separaron los the white stripes?",
            "la banda the white stripes oficializó su disolución en febrero de 2011.",
            "de qué nacionalidad son los cardigans?",
            "the cardigans es un grupo originario en suecia en el año 1992.",
            "recomiendame una canción",
            "espero te guste esta canción 😊 https://youtu.be/dqw4w9wgxcq",
            "cuántos soundtracks tiene 31 minutos?",
            "31 minutos cuenta con 4 álbumes de estudio, 1 en directo, 2 recopilatorios, 9 sencillos, 1 tributo y 2 colaboraciones",
            "en qué año salió ok computer?",
            "el disco ok computer se publicó el 16 de junio de 1997 en reino unido por radiohead.",
            "en cuántas bandas estuvo chris cornell?",
            "chris cornell estuvo en 3 grupos musicales diferentes.",
            "mejor disco de beyoncé",
            "el disco más vendido de beyoncé ha sido 'dangerously in love'",
            "quién es kanye west?",
            "kanye west es un rapero, productor, actor, diseñador y empresario estadounidense.",
            "qué es el japanoise?",
            "como su nombre sugiere, el “ruido” es un género musical que explora los límites entre “música” y “no música”.\nlos instrumentos utilizados varían ampliamente. noise presenta una fusión de instrumentos tradicionales y sonidos electrónicos, grabaciones y máquinas. a veces se describe como un escape sonoro, ya que el ritmo y la estructura son de menor importancia.",
            "quién es axl rose?",
            "william bruce bailey, mejor conocido como axl rose, es un cantante, compositor y pianista estadounidense.",
            "quiénes son masive attack?",
            "masive attack es una banda inglesa, considerados padres del género trip-hop.",
            "quiénes son weezer?",
            "weezer son una banda de rock alternativo estadounidense formada en 1992.",
            "por qué se separaron the beatles?",
            "popularmente se dice que fue culpa de 'yoko ono', pero no deja de ser solo una teoría. paul mccartney "
            "declaró en una entrevista que fue john (lennon) quien un día llegó al estudio y dijo 'me voy del grupo'.",
            "cuándo va a regresar one direction?",
            "nunca muajajajaja",
            "quiénes son black sabbath?",
            "black sabbath fue una banda británica de heavy metal y hard rock formmada en 1968.",
            "para qué sirve parental advisor?",
            "parental advisory: explicit content es una etiqueta de clasificación pegada por la asociación de "
            "industria magnetofónica de américa en muchos álbumes de estudio de artistas y grupos musicales que "
            "presentan lenguaje soez.",
            "quién invento el tocadiscos?",
            "en 1877, thomas alva edison patentó el fonógrafo, un invento capaz de grabar y reproducir posteriormente "
            "los sonidos que se grababan sobre cilindros.\npero las cosas no pararían ahí, en 1883 los científicos "
            "chichester alexander bell, su primo alexander graham bell y su socio charles tainter mejoraron el "
            "fonógrafo de edison dando paso al grafófono y crearon la volta graphophone company en 1886.\ndos años "
            "después otro avance llegó con la astucia de emile berliner, que llamó a su mejora gramófono, "
            "éste era capaz de trabajar con un disco de goma vulcanizada de 5” y era impulsado de forma manual.",
        ])
